### ISSUE TITLE
FormData is not defined

### ISSUE THREAD

**Issue by farazfarid** [run-llama/create_llama_projects#33]
Hello there,

I am using the nextjs-edge-template and getting the following message in my new project:
`Error reading file ./data/101.pdf: ReferenceError: FormData is not defined`

I get this error even on an older project where `npm run generate` definitely works.

Do you have an idea on what has changed or which package is causing this issue?

Kind regards

**Comment by marcusschiesser** [comment]
which nodejs are you using? `FormData` is part of it since v18

**Comment by farazfarid** [comment]
Thankyou so much! I totally forgot I switched the versions last week due to another project I was working on
